---
title: "Limpieza y Construcción de la Base Unificada"
author: "Zarela Palomino"
output: 
  rmdformats::readthedown:
    highlight: espresso
---

```{r}
setwd("/Users/zarelapalomino/Desktop/2025-2/Estadistica2/ZarelaPalomino_EfectosConflictoPeru")
```

# LIMPIEZA DE DATOS 
## LIBRERIAS
```{r}
library(readxl)
library(dplyr)
library(stringr)
library(janitor)
library(purrr)
library(readr)
```

## DATA CENSOS 1993 Y 2017 

```{r}
censos = read_excel ("data/Censo 1993 - departamentos urbano y rural.xlsx")  %>% 
  clean_names()
```

```{r}
censos = censos %>%
  mutate(
    disminucion_rural = (rural_2017 - rural_1993) / rural_1993 * 100
  )
```
## Seleccionando solo 6 departamentos
```{r}
departamentos_seleccionados = c(
  "ayacucho", "huancavelica", "apurímac",
  "lima", "piura", "lambayeque"
)

censos = censos %>%
  filter(departamentos %in% departamentos_seleccionados)
```

### cconvertir a númericos 
```{r}
censos = censos %>% 
  mutate(across(
    .cols = c(total_1993, urbana_1993, rural_1993,
             total_2017, urbana_2017, rural_2017),
    .fns = ~ as.numeric(str_replace_all(., "[^0-9\\.]", ""))
  ))
```

```{r}
names(censos)
```

## DATA MUE_DES_EST

```{r}
library(haven)

mue = read_sav("/Users/zarelapalomino/Desktop/2025-2/Estadistica2/ZarelaPalomino_EfectosConflictoPeru/data/mue_des_est.sav")
```

```{r}
names(mue)
```

```{r}
mue = mue %>%
  select(DEPHEC, IDPERSON)
```

```{r}
mue = mue %>%
  mutate(DEPHEC = as.character(as_factor(DEPHEC)))
```

```{r}
unique(mue$DEPHEC)
```

```{r}
table(mue$DEPHEC)
```


```{r}
deps_analisis = c("APURÍMAC", "AYACUCHO", "HUANCAVELICA",
                   "LAMBAYEQUE", "LIMA", "PIURA")

mue = mue %>%
  filter(DEPHEC %in% deps_analisis)


victimas_CVR = mue %>%
  count(DEPHEC, name = "victimas_CVR") %>%
  rename(departamentos = DEPHEC)

victimas_CVR = victimas_CVR %>% 
  mutate(departamentos = tolower(departamentos))
```

## DATA ACTOS_EST

```{r}
actos = read_sav("data/actos_est.sav")
```

```{r}
actos = actos %>%
  select(UBIDEP, IDPERSON)
```

```{r}
actos <- actos %>%
  mutate(UBIDEP = as.character(as_factor(UBIDEP)))

unique(actos$UBIDEP)
```
```{r}
deps_CVR = c("APURÍMAC", "AYACUCHO", "HUANCAVELICA",
               "LAMBAYEQUE", "LIMA", "PIURA")

actos_6 = actos %>%
  filter(UBIDEP %in% deps_CVR)
```

```{r}
actos_6 = actos_6 %>%
  mutate(departamentos = case_when(
    UBIDEP == "APURÍMAC"     ~ "apurímac",
    UBIDEP == "AYACUCHO"     ~ "ayacucho",
    UBIDEP == "HUANCAVELICA" ~ "huancavelica",
    UBIDEP == "LAMBAYEQUE"   ~ "lambayeque",
    UBIDEP == "LIMA"         ~ "lima",
    UBIDEP == "PIURA"        ~ "piura"
  ))
```

```{r}
intervenciones_cvr = actos_6 %>%
  group_by(departamentos) %>%
  summarise(intervenciones_cvr = n())

print(intervenciones_cvr)
```

## Guardando data
```{r}
write.csv(censos, "data_new/censos.csv", row.names = FALSE, fileEncoding = "UTF-8")
write.csv(intervenciones_cvr, "data_new/intervenciones_CVR.csv", row.names = FALSE, fileEncoding = "UTF-8")
write.csv(victimas_CVR, "data_new/victimas_CVR.csv", row.names = FALSE, fileEncoding = "UTF-8")
```

# UNIMOS LAS BASES DE DATOS

```{r}
base_unificada = censos %>%
  left_join(intervenciones_cvr, by = "departamentos") %>%
  left_join(victimas_CVR, by = "departamentos")
```

```{r}
base_unificada <- base_unificada %>%
  mutate(
    rural_prop_1993 = rural_1993 / total_1993,
    rural_prop_2017 = rural_2017 / total_2017
  )
```

```{r}
summary(base_unificada)
```
```{r}
write.csv(base_unificada, "data_new/base_unificada.csv", row.names = FALSE)
```



